version: '3.8'  # Use the desired version of Docker Compose syntax

services:
  mysql-db:
    image: mariadb:10.6
    container_name: mysql-db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: telmoudy
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  mysql_data:
  postgres_data_enset:
  pgadmin_data:

